site_name: TAME Documentation
site_url: https://yqshao.github.io/tame
repo_url: https://github.com/yqshao/tame
repo_name: yqshao/tame
nav:
  - Home: index.md
  - Recipes:
      - Overview: recipe/overview.md
      - Dynamics:
        - tame mdc: recipe/mdc.md
        - tame jacf: recipe/jacf.md
        - tame onsager: recipe/onsager.md
        - tame persist: recipe/persist.md
        - tame pmsd: recipe/pmsd.md
      - Structure:
        - tame rdf: recipe/rdf.md
        - tame sfac: recipe/sfac.md
  - Library:
      - Overview: lib/overview.md
      - Data types:
        - tame.Trajectory: lib/trajectory.md
        - tame.Operation: lib/operation.md
      - Modules:
        - tame.io: lib/io.md
        - tame.ops: lib/ops.md
        - tame.units: lib/units.md
      - Examples:
        - Hydroxyl ion: lib/hydroxyl.md
        - 2D RDF: lib/2d_rdf.md
  - About:
    - About TAME: about.md
    - Contributing: contributing.md
plugins:
  - mike
  - bibtex:
      bib_file: "docs/references.bib"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
  custom_dir: docs/overrides
markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.superfences
extra:
  version:
    provider: mike
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
