site_name: TAME Documentation
site_url: https://yqshao.github.io/tame
nav:
  - Home: index.md
  - Recipes:
    - Overview:     recipe/overview.md
    - tame jacf:    recipe/jacf.md
    - tame mdc:     recipe/mdc.md
    - tame sfac:    recipe/sfac.md
    - tame rdf:     recipe/rdf.md
    - tame pmsd:    recipe/pmsd.md
    - tame persist: recipe/persist.md
  - Developing:
    - Overview: developing/overview.md
    - Concepts: developing/concepts.md
    - Backends: developing/backends.md
    - Write a recipe: developing/write_a_recipe.md
  - Contributing: contributing.md
  - About: about.md
plugins:
  - mike
  - bibtex:
      bib_file: "docs/references.bib"
theme:
  name: material
markdown_extensions:
  - toc:
      toc_depth: 2
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.superfences
extra:
  version:
    provider: mike
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
